# Generated by Django 4.0.5 on 2022-06-15 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeorganizacao',
            name='diasEsperaAgendadas',
            field=models.PositiveSmallIntegerField(db_column='dias_espera_agendadas', default=1, verbose_name='Doação Agendada - Dias de Espera'),
        ),
        migrations.AlterField(
            model_name='unidadeorganizacao',
            name='metaQtdeCestas',
            field=models.PositiveSmallIntegerField(db_column='meta_qtde_cestas', default=1, verbose_name='Meta em Quantidade de Cestas'),
        ),
        migrations.CreateModel(
            name='FamiliaAtendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('qtdeCestas', models.PositiveSmallIntegerField(db_column='qtde_cestas', default=1, help_text='Informe a quantidade de cestas necessárias', verbose_name='Quantidade Cestas')),
                ('logradouro', models.CharField(help_text='Informe o logradouro e número do endereço', max_length=50, verbose_name='Logradouro')),
                ('complemento', models.CharField(help_text='Informe o complemento do endereço', max_length=30, verbose_name='Complemento')),
                ('bairro', models.CharField(help_text='Informe o bairro do endereço', max_length=30, verbose_name='Bairro')),
                ('telefone', models.CharField(help_text='Informe os telefones de contato', max_length=50, verbose_name='Telefone')),
                ('observacoes', models.CharField(help_text='Informe observações importantes', max_length=255, verbose_name='Observações')),
                ('unidadeOrganizacao', models.ForeignKey(db_column='unidade_org_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='pages.unidadeorganizacao', verbose_name='Unidade Organização')),
            ],
        ),
    ]
