# Generated by Django 4.0.5 on 2022-06-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_unidadeorganizacao_diasesperaagendadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiaatendida',
            name='complemento',
            field=models.CharField(help_text='Informe o complemento do endereço', max_length=30, null=True, verbose_name='Complemento'),
        ),
    ]
