# Generated by Django 4.1.2 on 2022-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_familiaquestionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiaquestionario',
            name='motivoLugarViolento',
            field=models.CharField(choices=[('ASSALT', 'Assaltos'), ('DROGAS', 'Tráfico/Uso Drogas'), ('PROSTI', 'Prostituição'), ('OUTROS', 'Outros')], default='x', max_length=6, verbose_name='Lugar Violência'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='tipoMoradia',
            field=models.CharField(choices=[('ALUGAD', 'Alugada'), ('CEDIDA', 'Cedida'), ('FINANC', 'Própria Financiada'), ('QUITAD', 'Própria Quitada')], max_length=6, verbose_name='Tipo Moradia'),
        ),
    ]
