# Generated by Django 4.0.5 on 2022-06-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_familiaatendida_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiaatendida',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Família Ativa?'),
        ),
        migrations.AlterField(
            model_name='familiaatendida',
            name='bairro',
            field=models.CharField(help_text='Informe o bairro do endereço', max_length=30, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='familiaatendida',
            name='logradouro',
            field=models.CharField(help_text='Informe o logradouro e número do endereço', max_length=50, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='familiaatendida',
            name='observacoes',
            field=models.CharField(help_text='Informe observações importantes', max_length=255, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='familiaatendida',
            name='telefone',
            field=models.CharField(help_text='Informe os telefones de contato', max_length=50, null=True, verbose_name='Telefone'),
        ),
    ]
