# Generated by Django 4.1.2 on 2022-11-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_familiaquestionario_preenchido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiaquestionario',
            name='tipoMoradia',
            field=models.CharField(choices=[('QUITAD', 'Própria Quitada'), ('FINANC', 'Própria Financiada'), ('ALUGAD', 'Alugada'), ('CEDIDA', 'Cedida')], max_length=6, null=True, verbose_name='1. Qual o tipo de moradia onde a família reside?'),
        ),
    ]
