# Generated by Django 4.1.2 on 2022-11-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_familiaquestionario_tipomoradia'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiaquestionario',
            name='temPessoasDoentes',
            field=models.BooleanField(default=False, null=True, verbose_name='Tem Pessoas Doentes'),
        ),
    ]
