# Generated by Django 4.1.2 on 2022-11-23 05:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_familiaquestionario_tempessoasdoentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiaquestionario',
            name='preenchido',
        ),
        migrations.AddField(
            model_name='familiaquestionario',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='criancasFrequentamEscola',
            field=models.CharField(choices=[('NAOHA', 'Não há crianças'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='frequentaReligiao',
            field=models.CharField(choices=[('NENHUM', 'Nenhuma'), ('CATOLI', 'Católica'), ('EVANGE', 'Evangélica'), ('TJEOVA', 'Testemunhas Jeová'), ('ESPIRI', 'Espírita'), ('OUTROS', 'Outras')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='maiorGrauEscolaridade',
            field=models.CharField(choices=[('FUN_IN', 'Fundamental Incompleto'), ('FUN_CP', 'Fundamental Completo'), ('MED_IN', 'Médio Incompleto'), ('MED_CP', 'Médio Completo'), ('SUP_IN', 'Superior Incompleto'), ('SUP_CP', 'Superior Completo')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='moradiaLugarViolento',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='pessoasMenores',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='4. Das pessoas que residem na casa, quantas são menores de 18 anos?'),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='pessoasNaCasa',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='3. Quantas pessoas vivem na casa?'),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='qtdeDoentes',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='6.1. Se sim, quantas pessoas doentes ou com necessidades especiais?'),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='qtdeTrabalham',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='7. Das pessoas que residem na casa, quantas trabalham e contribuem com a renda familiar?'),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='qtdeTrabalhoAutonomo',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='9. Das pessoas que trabalham, quantas são autônomas?'),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='qtdeTrabalhoFormal',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='8. Das pessoas que trabalham, quantas trabalham em empregos formais com carteira assinada?'),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='qtdeTrabalhoInformal',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='10. Das pessoas que trabalham, quantas trabalham informalmente sem vínculo empregatício ou fazendo bicos?'),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='recebeAuxilioGoverno',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='rendaBrutaFamiliar',
            field=models.CharField(choices=[('MENOS1', 'Até um salário mínimo'), ('EXATO1', 'Um salário mínimo'), ('EXATO2', 'Dois salários mínimos'), ('EXATO3', 'Três salários mínimos'), ('ACIMA3', 'Acima de três salários mínimos')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='temPessoasDoentes',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='familiaquestionario',
            name='valorMoradia',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Em caso de financiamento ou aluguel informe o valor pago mensalmente:'),
        ),
    ]
