# Generated by Django 4.1.2 on 2022-11-25 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_familiaquestionario_preenchido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiaatendida',
            name='dataCadastro',
            field=models.DateField(auto_now_add=True, db_column='data_cadastro', default=django.utils.timezone.now, verbose_name='Data Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiaatendida',
            name='dataDesativacao',
            field=models.DateField(db_column='data_desativacao', default=None, help_text='Informe a data de desativação da família no sistema', verbose_name='Data Desativação'),
            preserve_default=False,
        ),
    ]
