# Generated by Django 4.1.2 on 2022-11-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_familiaatendida_datacadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiaatendida',
            name='dataDesativacao',
            field=models.DateField(db_column='data_desativacao', help_text='Informe a data de desativação da família no sistema', null=True, verbose_name='Data Desativação'),
        ),
    ]
