# Generated by Django 4.1.2 on 2022-11-25 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_familiaatendida_datadesativacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiaatendida',
            name='dataDesativacao',
            field=models.DateField(db_column='data_desativacaso', default=datetime.date(2022, 11, 25), help_text='Informe a data de desativação da família no sistema', null=True, verbose_name='Data Desativação'),
        ),
    ]
